"""Hunt timing constants"""

from __future__ import annotations

from pybot.recognition.rules import HUNT_OBJECT_RADIUS, HUNT_TRACK_LOST_LIMIT

HUNT_DISCOVERY_INTERVAL_MS = 1000
HUNT_TELEPORT_DURATION_MS = 800
WORKER_SHUTDOWN_TIMEOUT_S = 2.0
CELL_SIZE_PX = 64
DEFAULT_SEARCH_RANGE_CELLS = 16
WORKER_POLL_INTERVAL_S = 0.05
LOG_REPEAT_INTERVAL_MS = 5000
SIT_LOW_SP_RATIO = 0.10
SIT_RESUME_SP_RATIO = 0.98
SIT_SP_POLL_INTERVAL_S = 0.25
SIT_IDLE_BEFORE_SIT_S = 1.0

__all__ = [
    "HUNT_DISCOVERY_INTERVAL_MS",
    "HUNT_OBJECT_RADIUS",
    "HUNT_TELEPORT_DURATION_MS",
    "WORKER_SHUTDOWN_TIMEOUT_S",
    "HUNT_TRACK_LOST_LIMIT",
    "CELL_SIZE_PX",
    "DEFAULT_SEARCH_RANGE_CELLS",
    "WORKER_POLL_INTERVAL_S",
    "LOG_REPEAT_INTERVAL_MS",
    "SIT_LOW_SP_RATIO",
    "SIT_RESUME_SP_RATIO",
    "SIT_SP_POLL_INTERVAL_S",
    "SIT_IDLE_BEFORE_SIT_S",
]
